### ISSUE TITLE
load_datasets function requires different data_path depending on the method used

### ISSUE THREAD

**Issue by joaopfonseca** [AlgoWit/publications#79]
The function `load_datasets` (located in the `utils.py` script) requires different ways of passing the variable `data_path` depending on whether one is using the `csv` or `db` method. If using `db` the file path must be provided, whereas the `csv` method only requires the directory.

Perhaps it would be best to standardize their behavior? This would be useful in situations where one might have to use both methods (as a loop, eventually) and could make up for cleaner code.

Should I do it?

**Comment by georgedouzas** [comment]
This is because, the initial assumption was that there is always a single `db` but multiple `csv` files.  Ok I agree, `data_path` should be replaced by `data_dir`. Then the `db` name or `csv` files names will be parsed. Let's also assume that there can be multiple `db` or `csv` files in the directory.

**Comment by georgedouzas** [comment]
Please change the scripts to be compatible with your proposed solution.
